openapi: 3.0.0
info:
  title: Tables API
  version: 1.0.0
tags:
  - name: Tables
    description: Table management for cafes

paths:
  /api/tables/add:
    post:
      summary: Add a new table
      description: Add a table.
      tags: [Tables]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - cafe_id
                - table_no
                - capacity
              properties:
                cafe_id:
                  type: string
                table_no:
                  type: string
                capacity:
                  type: number
                is_available:
                  type: boolean
              example:
                cafe_id: "cafe123"
                table_no: "T1"
                capacity: 4
                is_available: true
      responses:
        201:
          description: Table added successfully.
        500:
          description: Error adding table.

  /api/tables/edit/{id}:
    put:
      summary: Update a table
      description: Update a table by its ID.
      tags: [Tables]
      parameters:
        - in: path
          name: id
          description: Table ID.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cafe_id:
                  type: string
                table_no:
                  type: string
                capacity:
                  type: number
                is_available:
                  type: boolean
              example:
                cafe_id: "cafe123"
                table_no: "T1"
                capacity: 4
                is_available: false
      responses:
        200:
          description: Table updated successfully.
        500:
          description: Error updating table.

  /api/tables/delete/{id}:
    delete:
      summary: Delete a table
      description: Delete a table identified by its ID.
      tags: [Tables]
      parameters:
        - in: path
          name: id
          description: Table ID.
          required: true
          schema:
            type: string
      responses:
        200:
          description: Table deleted successfully.
        500:
          description: Error deleting table.

  /api/tables/{id}/search:
    get:
      summary: Search tables for a cafe
      description: Search for tables within a specific cafe.
      tags: [Tables]
      parameters:
        - in: path
          name: id
          description: Cafe ID.
          required: true
          schema:
            type: string
        - in: query
          name: q
          description: Search query.
          schema:
            type: string
        - in: query
          name: page
          description: Page number.
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          description: Items per page.
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: Returns search results with table details.
        500:
          description: Error searching tables.

  /api/tables/{id}:
    get:
      summary: List tables for a cafe
      description: Retrieve a paginated list of tables for a specified cafe.
      tags: [Tables]
      parameters:
        - in: path
          name: id
          description: Cafe ID.
          required: true
          schema:
            type: string
        - in: query
          name: page
          description: Page number.
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          description: Items per page.
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: List of tables.
        500:
          description: Error fetching tables.